# Config version 1.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install Pipfile dependencies with pipenv
          command: pipenv install
      - run:
          name: Activate virtual environment
          command: pipenv shell
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/
          key: v1-dependencies-{{ checksum "Pipfile" }}

