# Config version 1.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-cache-{{ checksum "Pipfile.lock" }}
          - v1-cache-
      - run:
          name: Install Pipfile dependencies with pipenv
          command: pipenv sync --dev
      - save_cache:
          key: v1-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

workflows:
  version: 2
  build:
    jobs:
      - build
